# -*- coding: utf-8 -*-
"""Manga_Project_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiQvqxIUq8F747laECxPotEJu7u_wlxA
"""

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import ast

# Page Configuration
st.set_page_config(page_title="Manga Recommender", page_icon="📚", layout="wide")

st.title("📚 Manga Recommender & Filter App")
st.markdown("Discover new manga based on your favorites or filter by your specific tastes!")

# 1. Load Data and Cache it so it only runs once!
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("Manga_data.csv.gz", compression="gzip")
    except FileNotFoundError:
        st.error("Manga_data.csv not found. Please upload it.")
        return pd.DataFrame()

    df['description'] = df['description'].fillna("")
    df['rating'] = df['rating'].fillna(0)
    df['year'] = pd.to_numeric(df['year'], errors='coerce').fillna(0)

    def get_tag_list(tag_str):
        try:
            return ast.literal_eval(tag_str)
        except:
            return []

    def process_tags(tag_str):
        tags = get_tag_list(tag_str)
        return " ".join([str(t).replace(" ", "_") for t in tags])

    df['processed_tags'] = df['tags'].apply(process_tags)
    df['tag_list'] = df['tags'].apply(get_tag_list)
    df['combined_features'] = df['processed_tags'] + " " + df['description']

    return df

df = load_data()

# 2. Compute TF-IDF Matrix (Cached for speed)
@st.cache_resource
def compute_tfidf(data):
    tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
    matrix = tfidf.fit_transform(data['combined_features'])
    return matrix

if not df.empty:
    tfidf_matrix = compute_tfidf(df)

    # Extract unique tags for the sidebar
    all_tags = set()
    for tags in df['tag_list']:
        all_tags.update(tags)
    all_tags = sorted(list(all_tags))

    # --- UI LAYOUT ---
    tab1, tab2 = st.tabs(["🎯 Content-Based Recommendations", "🔍 Filter Manga"])

    # TAB 1: RECOMMENDATIONS
    with tab1:
        st.subheader("Find Similar Manga")
        col1, col2 = st.columns([3, 1])

        with col1:
            manga_titles = df['title'].dropna().unique().tolist()
            selected_manga = st.selectbox("Select a Manga you like:", [""] + manga_titles)
        with col2:
            num_recs = st.slider("Number of Recommendations:", 1, 20, 5)

        if selected_manga:
            idx = df.index[df['title'] == selected_manga].tolist()[0]
            cosine_sim = linear_kernel(tfidf_matrix[idx], tfidf_matrix).flatten()
            sim_indices = cosine_sim.argsort()[:-num_recs-2:-1][1:]

            recs = df.iloc[sim_indices]

            st.write(f"### Because you liked **{selected_manga}**:")
            # Display results in a nice grid
            cols = st.columns(5)
            for i, (_, row) in enumerate(recs.iterrows()):
                with cols[i % 5]:
                    html_image = f'<img src="{row["cover"]}" width="100%" referrerpolicy="no-referrer" style="border-radius: 8px;">'
                    st.markdown(html_image, unsafe_allow_html=True)
                    st.markdown(f"**{row['title']}**")
                    st.caption(f"⭐ {row['rating']} | 📅 {int(row['year']) if row['year'] else 'N/A'}")

    # TAB 2: FILTERING
    with tab2:
        st.subheader("Filter Manga by Criteria")

        # Move filters to a nice row
        f_col1, f_col2, f_col3 = st.columns(3)
        with f_col1:
            min_rating = st.slider("Minimum Rating", 0.0, 5.0, 4.0, 0.1)
        with f_col2:
            years = st.slider("Release Year Range", 1950, 2024, (2000, 2024))
        with f_col3:
            selected_tags = st.multiselect("Must include tags:", all_tags)

        if st.button("Apply Filters", use_container_width=True):
            filtered = df[
                (df['rating'] >= min_rating) &
                (df['year'] >= years[0]) &
                (df['year'] <= years[1])
            ]

            if selected_tags:
                filtered = filtered[filtered['tag_list'].apply(lambda x: all(t in x for t in selected_tags))]

            if filtered.empty:
                st.warning("No manga matched your criteria.")
            else:
                st.success(f"Found {len(filtered)} matching manga! Showing top 20:")
                res = filtered.sort_values(by='rating', ascending=False).head(20)

                cols = st.columns(5)
                for i, (_, row) in enumerate(res.iterrows()):
                    with cols[i % 5]:
                        html_image = f'<img src="{row["cover"]}" width="100%" referrerpolicy="no-referrer" style="border-radius: 8px;">'
                        st.markdown(html_image, unsafe_allow_html=True)
                        st.image(row['cover'], use_container_width=True)
                        st.markdown(f"**{row['title']}**")
                        st.caption(f"⭐ {row['rating']}")

